# Generated by Django 4.1.2 on 2022-11-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_profile_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sale',
            new_name='sale_slug',
        ),
    ]
