# Generated by Django 4.1.2 on 2022-11-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_sale_comment_sale_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sale_slug',
            new_name='sale',
        ),
    ]
