# Generated by Django 4.1.2 on 2022-11-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_rename_sale_slug_comment_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_percent',
            field=models.IntegerField(null=True),
        ),
    ]
