# Generated by Django 4.1.2 on 2022-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_sale_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='access_for_post',
            field=models.BooleanField(default=False),
        ),
    ]
