# Generated by Django 4.1.2 on 2022-11-29 21:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_sale_cat_alter_sale_sale_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True, verbose_name='URL'),
        ),
    ]
