# Generated by Django 4.1.2 on 2022-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_sale_access_for_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
